version: '3'
services:
    apache:
        image: mluex/apache-dev
        container_name: website_apache
        ports:
          - 8080:80
          - 8443:443
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/website
        depends_on:
          - php
        environment:
          TZ: Europe/Berlin

    php:
        image: mluex/php-dev:7.2
        container_name: website_php
        volumes:
          - .:/home/wwwroot/website
          - .docker/config/php/php.ini:/usr/local/etc/php/php.ini
          - .docker/config/php/php-fpm-pool.ini:/usr/local/etc/php/pool.d/www.conf
        environment:
          - TZ=Europe/Berlin